### ISSUE TITLE
MPCPY with windows - pyfmi error: no binary for this platform.

### ISSUE THREAD

**Issue by Eramismus** [lbl-srg/MPCPy#109] opened 2018-01-31 20:56 UTC
Hello,

I have been trying to get mpcpy working on a Windows 10 64-bit machine and after some meddling around with JModelica etc. I have reached a stage where the introductory tutorial throws an error when loading a fmu with pyfmi: 
```

mpcpy\utility.py", line 396, in _create_fmu
self.fmu = load_fmu(self.fmupath);
File "src\pyfmi\fmi.pyx", line 7253, in pyfmi.fmi.load_fmu (src\pyfmi\fmi.c:79503)
File "src\pyfmi\fmi.pyx", line 6310, in pyfmi.fmi.FMUModelME2.__init__ (src\pyfmi\fmi.c:68663)
File "src\pyfmi\fmi.pyx", line 3449, in pyfmi.fmi.FMUModelBase2.__init__ (src\pyfmi\fmi.c:37933)
FMUException: Error loading the binary. The FMU contains no binary for this platform.
```

Something similar was discussed in this thread: http://www.jmodelica.org/25878. And apparently the error there was due to trying access a FMU which had different binary folders specified and pyfmi was not able to find the right binaries. 

So I am using a 64-bit Windows 10 but running a Python 2.7 32-bit conda environment to make sure everything works ok but still get the error. I was just wondering this might be the case also here? Were all the FMUs provided with the tutorial compiled only with linux64 binaries? Would you happen to know if there is a way around this error at this stage? I naturally could just create my own weather processors too but that would be quite onerous... Below is the full error message and my system specs if it helps. 

Thank you very much already!

Conda/Python details:
```
platform: win-32
conda version : 4.3.31
conda is private : False
conda-env version : 4.3.31
conda-build version : not installed
python version : 2.7.14.final.0
```

System Info:
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
System Type:               x64-based PC
```

Error in detail:
```
File "introductory.py", line 167, in __main__
Failed example:
    weather.collect_data(start_time, final_time) # doctest: +ELLIPSIS
Exception raised:
    Traceback (most recent call last):
      File "usr\Continuum\miniconda2\envs\mpcpy32\lib\doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__[24]>", line 1, in <module>
        weather.collect_data(start_time, final_time) # doctest: +ELLIPSIS
      File "usr\MPCPy-0.1.0\MPCPy-0.1.0\mpcpy\exodata.py", line 258, in collect_data
        self._collect_data(start_time, final_time);
      File "usr\MPCPy-0.1.0\MPCPy-0.1.0\mpcpy\exodata.py", line 782, in _collect_data
        self._process_weather_data();
      File "usr\MPCPy-0.1.0\MPCPy-0.1.0\mpcpy\exodata.py", line 447, in _process_weather_data
        self._create_fmu({'fmupath': weatherdir+os.sep+fmuname});
      File "usr\MPCPy-0.1.0\MPCPy-0.1.0\mpcpy\utility.py", line 396, in _create_fmu
        self.fmu = load_fmu(self.fmupath);
      File "src\pyfmi\fmi.pyx", line 7253, in pyfmi.fmi.load_fmu (src\pyfmi\fmi.c:79503)
      File "src\pyfmi\fmi.pyx", line 6310, in pyfmi.fmi.FMUModelME2.__init__ (src\pyfmi\fmi.c:68663)
      File "src\pyfmi\fmi.pyx", line 3449, in pyfmi.fmi.FMUModelBase2.__init__ (src\pyfmi\fmi.c:37933)
    FMUException: Error loading the binary. The FMU contains no binary for this platform.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "usr\miniconda2\envs\mpcpy32\lib\threading.py", line 801, in __bootstrap_inner    self.run()
  File "C:\JModelica.org-2.0\install\Python\pymodelica\compiler_logging.py", line 218, in run
    xml.sax.parse(self.stream, LogErrorParser(self.result))
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\expatreader.py", line 116, in parse
    self._close_source()
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\expatreader.py", line 235, in _close_source
    file.close()
AttributeError: KeepLastStream instance has no attribute 'close'


Exception in thread Thread-2:
Traceback (most recent call last):
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\threading.py", line 801, in __bootstrap_inner    self.run()
  File "\JModelica.org-2.0\install\Python\pymodelica\compiler_logging.py", line 218, in run
    xml.sax.parse(self.stream, LogErrorParser(self.result))
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\expatreader.py", line 116, in parse
    self._close_source()
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\expatreader.py", line 235, in _close_source
    file.close()
AttributeError: KeepLastStream instance has no attribute 'close'


Exception in thread Thread-3:
Traceback (most recent call last):
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\threading.py", line 801, in __bootstrap_inner    self.run()
  File "C:\JModelica.org-2.0\install\Python\pymodelica\compiler_logging.py", line 218, in run
    xml.sax.parse(self.stream, LogErrorParser(self.result))
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\expatreader.py", line 116, in parse
    self._close_source()
  File "usr\Continuum\miniconda2\envs\mpcpy32\lib\xml\sax\expatreader.py", line 235, in _close_source
    file.close()
AttributeError: KeepLastStream instance has no attribute 'close'
```

-Eramismus

**Comment by dhblum** [comment] 2018-01-31 21:50
Thank you for reporting!

Windows compatability issues are being dealt with in https://github.com/lbl-srg/MPCPy/issues/26.  The branch containing the fixes described there is called ``issue26_windowsCompatability``.  This branch is still under development and has not been merged to master yet, as all testing has not yet been completed and passed.  In addition, installation instructions have not been written for Windows.  I am working to have have a stable version soon though that can be merged to master and released with the next version.

We have, however, added fmus that are compatible with Windows in that branch, and the introductory tutorial should work.  Therefore, I will close this issue as a duplicate of https://github.com/lbl-srg/MPCPy/issues/26.

I recommend for now to try out branch  ``issue26_windowsCompatability`` and see if you get the introductory tutorial to work on your machine.  If not, continued feedback would be very helpful.  Please report further Windows-specific issues in https://github.com/lbl-srg/MPCPy/issues/26.

**Closed by dhblum** 2018-01-31 21:50 UTC
Labels: duplicate

**Comment by Eramismus** [comment] 2018-02-01 09:52
Thank you! Used the Windows branch and it worked out fine. Two tests still failed basically due to truncation error but otherwise ran like a charm! And thanks for the work you guys are doing.
